// Mocks generated by Mockito 5.2.0 from annotations
// in testing_example/test/atm_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:testing_example/atm.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Bank].
///
/// See the documentation for Mockito's code generation for more information.
class MockBank extends _i1.Mock implements _i2.Bank {
  MockBank() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get balance =>
      (super.noSuchMethod(Invocation.getter(#balance), returnValue: 0.0)
          as double);
  @override
  bool verifyPassword(int? pass) =>
      (super.noSuchMethod(Invocation.method(#verifyPassword, [pass]),
          returnValue: false) as bool);
  @override
  double doDebit(double? amount) => (super
          .noSuchMethod(Invocation.method(#doDebit, [amount]), returnValue: 0.0)
      as double);
  @override
  double doCredit(double? amount) =>
      (super.noSuchMethod(Invocation.method(#doCredit, [amount]),
          returnValue: 0.0) as double);
}
